---
title: "R Notebook"
output: html_notebook
---

```{r}
library(gapminder); library(tidyverse)

```

```{r}
gapminder

```

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp)) + geom_point()

```
```{r}
ggplot(data = gapminder) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, size = pop))
```
```{r}
ggplot(data = gapminder, aes(x = year, y = lifeExp, group = country)) + 
  geom_line(aes(alpha = if_else(country == "Rwanda", 1, 0.3))) +
  guides(alpha = "none")

```
```{r}
ggplot(data = gapminder, aes(x = year, y = lifeExp, group = continent))

```
```{r}
gapminder %>% 
  group_by (continent, year) %>% 
  summarise(meanGDPperCap = mean(gdpPercap, na.rm = T)) %>% 
  ggplot(data = ., aes(x = year, y = meanGDPperCap, group = continent, colour = continent))+
  geom_line()


```
```{r}
gapminder %>% 
  group_by (continent, year) %>% 
  summarise(meanGDPperCap = mean(gdpPercap, na.rm = T)) %>% 
  ggplot(data = ., aes(x = year, group = continent, colour = continent))+
  geom_histogram()

```
```{r}
ggplot(data = gapminder, aes(x=pop, group=continent, colour=continent))+
  geom_histogram()+
  scale_x_log10()

```
```{r}
gapminder %>% 
  group_by (continent, year) %>% 
  summarise(meanlifeExp = mean(lifeExp, na.rm = T)) %>% 
  ggplot(data = ., aes(x = continent, y = meanlifeExp, group = continent, colour = continent))+
  geom_col()

```
```{r}
gapminder %>% 
  group_by (lifeExp, year) %>% 
  summarise(meanlifeExp = mean(lifeExp, na.rm = T)) %>% 
  ggplot(data = ., aes(x = year, y = meanlifeExp))+
  geom_col()


```

