---
title: "Walkthrough of cleaning Mexico EITI data"
author: |
  | Hari Subhash
  | Data Scientist @NRGI
date: "`r Sys.Date()`"
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
  html_document:
    df_print: paged
    includes: /Users/hsubhash/Documents/GitHub/Common Assets/header.html
css: /Users/hsubhash/Documents/GitHub/Common Assets/custom.css
---


```{r, message=FALSE}
rm(list = ls())
library(tidyverse); library(sf); library(sp); library(rnaturalearth)

eitiImport <- read_csv("http://eiti.transparenciapresupuestaria.gob.mx/es/eiti/ficha_recurso/_rid/13/_mto/3/_mod/descargar?tipo=recurso_csv&id=4", locale = locale(encoding = "latin1"))

rcData <- read_csv("rcMX.csv")
```

```{r}
names(eitiImport)
```


```{r}
mxMap <- ne_states(country = "Mexico", returnclass = "sf")

ggplot() +
    geom_sf(data = mxMap) +
    
```



```{r}
mainTable <- eitiImport %>% 
    ##select and rename all columns of interest
    select(contractID = ID_CONTRATO, 
           companyName = DESC_ORGANIZACION, 
           state = ENTIDAD_FEDERATIVA_ENTREGA_ITEMS_PROCED) %>%
    ##group by contractID
    group_by(contractID) %>%
    ##create variable that records no. of observations per contract ID
    mutate(nObs = n()) %>% 
    ##ungroup contractID so that it can be mutated
    ungroup() %>% 
    ##combine contract ID and state for non-unique contract IDs
    mutate(contractIDNew = if_else(nObs > 1, paste(contractID, state, sep="-"), contractID)) 

##create a mapping between the old and new ids
idMapping <-  mainTable %>% 
    select(contractIDOld = contractID, contractIDNew)

##select the contract ID and company name
mainTable <-  mainTable %>% 
    select(contractID = contractIDNew, companyName)
```



```{r}
eitiImport %>% 
    group_by(ID_CONTRATO) %>% 
    filter(n() > 1) %>% 
    select()
```

```{r}
unique(rcData$`Project Identifier`)
```

```{r}
unique(eitiImport$FUENTE_INFORMACION)
```


```{r}
names(eitiImport)
```


```{r}
classSeparate <- eitiImport %>% 
    filter(!ID_TIPO_CONTRATO %in% 8:10) %>% 
    select(orgName = DESC_ORGANIZACION, contractID = ID_CONTRATO) %>%
    mutate(oldName = orgName) %>% 
    separate_rows(orgName, sep = " y ") %>% 
    group_by(contractID) %>% 
    mutate(companyNum = paste0("company", row_number())) %>% 
    spread(key = companyNum, value = orgName)
```


```{r}
testAnswer <- rcData %>% 
    select(contractID = `Contract Identifier`, companyName = `Company Name 1`) %>% 
    mutate(companyCombined = companyName) %>% 
    separate_rows(companyName, sep = " y ") %>% 
    group_by(contractID) %>% 
    mutate(companyID = paste0("company", row_number())) %>% 
    spread(companyID, companyName)
```


```{r}
testAnswer <- rcData %>% 
    select(`Contract Name`, companyName = `Company Name 1`) %>% 
    mutate(companyList = str_split(companyName, pattern = " y ")) %>% 
    unnest(companyList) %>% 
    group_by(companyName) %>% 
    mutate(row = row_number()) %>%
    spread(row, companyList)
    
```

```{r}
names(rcData)
```

The non-Pemex contracts are identifiable by contract type id. All Pemex contracts have a contract type ID that is either 8, 9 or 10. So we select all the contract that are not these three to identify non-Pemex.

```{r}
nonPemex <- eitiImport %>% 
    filter(!ID_TIPO_CONTRATO %in% 8:10)
```


### Lets get everything into shape

```{r}
splitNames <- str_split(nonPemex$DESC_ORGANIZACION, pattern = " y ")
```



####Tidy up the RC data

```{r}
unique(rcData$`Company Name 2`)

listOfCompExtensions <- c("S. de R.L. de C.V.", "S.A. de C.V.", "S.A.P.I. de C.V.", "S.A.PI. de C.V.", "S.AP.I. de C.V.")
```


